### ISSUE TITLE
error in /courses/streaming/process/sandiego

### ISSUE THREAD

**Issue by noopur100392** [GoogleCloudPlatform/training-data-analyst#2347]
Hi Team,

I am getting below error when I ran  command " ./run_oncloud.sh $DEVSHELL_PROJECT_ID $BUCKET AccidentAlert --bigtable"  from location /courses/streaming/process/sandiego

Can someone please help, its really urgent for me..

[WARNING] 
java.lang.ClassNotFoundException: com.google.cloud.training.dataanalyst.sandiego.--bigtable
    at java.net.URLClassLoader.findClass (URLClassLoader.java:476)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:589)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:522)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:270)
    at java.lang.Thread.run (Thread.java:829)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.336 s
[INFO] Finished at: 2023-07-17T19:06:52Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project sandiego: An exception occured while executing the Java class. com.google.cloud.training.dataanalyst.sandiego.--bigtable -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project sandiego: An exception occured while executing the Java class. com.google.cloud.training.dataanalyst.sandiego.--bigtable

**Comment by zdoryk** [comment]
## Almost the same for me
```
java.lang.RuntimeException: Failed to create a workflow job: (8fde5173b205c4ba): The workflow could not be created.
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:961)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:182)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:317)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:303)
        at com.google.cloud.training.dataanalyst.sandiego.CurrentConditions.main(CurrentConditions.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "(8fde5173b205c4ba): The workflow could not be created.",
    "reason" : "notFound"
  } ],
  "message" : "(8fde5173b205c4ba): The workflow could not be created.",
  "status" : "NOT_FOUND"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:443)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
        at org.apache.beam.runners.dataflow.DataflowClient.createJob(DataflowClient.java:61)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:947)
        ... 10 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.544 s
[INFO] Finished at: 2024-09-10T09:40:39+00:00
[INFO] Final Memory: 47M/405M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project sandiego: An exception occured while executing the Java class. Failed to create a workflow job: (8fde5173b205c4ba): The workflow could not be created. 404 Not Found
[ERROR] {
[ERROR] "code" : 404,
[ERROR] "errors" : [ {
[ERROR] "domain" : "global",
[ERROR] "message" : "(8fde5173b205c4ba): The workflow could not be created.",
[ERROR] "reason" : "notFound"
[ERROR] } ],
[ERROR] "message" : "(8fde5173b205c4ba): The workflow could not be created.",
[ERROR] "status" : "NOT_FOUND"
[ERROR] }
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project sandiego: An exception occured while executing the Java class. Failed to create a workflow job: (8fde5173b205c4ba): The workflow could not be created.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. Failed to create a workflow job: (8fde5173b205c4ba): The workflow could not be created.
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:339)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.RuntimeException: Failed to create a workflow job: (8fde5173b205c4ba): The workflow could not be created.
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:961)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:182)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:317)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:303)
        at com.google.cloud.training.dataanalyst.sandiego.CurrentConditions.main(CurrentConditions.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "(8fde5173b205c4ba): The workflow could not be created.",
    "reason" : "notFound"
  } ],
  "message" : "(8fde5173b205c4ba): The workflow could not be created.",
  "status" : "NOT_FOUND"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:443)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
        at org.apache.beam.runners.dataflow.DataflowClient.createJob(DataflowClient.java:61)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:947)
        ... 10 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

## I fixed it with:
```
gcloud services disable dataflow.googleapis.com --force
gcloud services enable dataflow.googleapis.com
```
I should have done this earlier, but I wasn't authorized in Cloud Shell, so the commands above were not executed.
