### ISSUE TITLE
Introduction to TensorFlow Data Validation (tfdv_basic_spending.ipynb) first code block (pip installs) falters

### ISSUE THREAD

**Issue by MrCsabaToth** [GoogleCloudPlatform/training-data-analyst#2423]
First numpy installations descends into a carnage:

```
Collecting numpy==1.19.2
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Running from numpy source directory.
      setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              for i in range(1, RK_STATE_LEN):
                  self.rng_state.key[i] = val[i]
              self.rng_state.pos = i
      
              self._bitgen.state = &self.rng_state
              self._bitgen.next_uint64 = &mt19937_uint64
                                         ^
      ------------------------------------------------------------
      
      _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_common.pyx
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_mt19937.pyx
      Traceback (most recent call last):
        File "/var/tmp/pip-install-v15bz4u6/numpy_84e38916771e4e8e82423af35aa7fc95/tools/cythonize.py", line 235, in <module>
          main()
        File "/var/tmp/pip-install-v15bz4u6/numpy_84e38916771e4e8e82423af35aa7fc95/tools/cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "/var/tmp/pip-install-v15bz4u6/numpy_84e38916771e4e8e82423af35aa7fc95/tools/cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/var/tmp/pip-install-v15bz4u6/numpy_84e38916771e4e8e82423af35aa7fc95/tools/cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "/var/tmp/pip-install-v15bz4u6/numpy_84e38916771e4e8e82423af35aa7fc95/tools/cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/conda/bin/python3.9', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/var/tmp/pip-build-env-mq886lme/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/var/tmp/pip-build-env-mq886lme/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/var/tmp/pip-build-env-mq886lme/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 499, in <module>
          setup_package()
        File "setup.py", line 479, in setup_package
          generate_cython()
        File "setup.py", line 274, in generate_cython
          raise RuntimeError("Running cythonize failed!")
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Then later when I try to execute the second code bloc where the `tensorflow_data_validation` would be imported fails. Looking at the solution: doesn't have any package versions pinned, and more importantly the `tensorflow-data-validation` has a `--user` switch.

**Comment by MrCsabaToth** [comment]
I propose using the solution pip install code with the lab.

**Comment by MrCsabaToth** [comment]
The https://github.com/GoogleCloudPlatform/training-data-analyst/commit/dc44f9e302a852854a0c492e307f49e0ffba2302 commit corrected the solution pip installs but not the lab's. Probably the committer tested the lab ipynb after the solution ipynb was executed in the same jupyterlab environment. Hence the pip install runs of the lab was already satisfied by the solution earlier. That's my suspicion.

**Comment by MrCsabaToth** [comment]
Hmmm, while trying to craft a PR it looks like the lab ipynb is already same as the solution:
```
!pip install pyarrow
!pip install numpy
!pip install tensorflow-data-validation --user
```

What I suspect that I either the default clone yielded a default branch which had an older file version (unlikely), or more likely I accidentally clicked the `[tfdv_basic_spending_old.ipynb](https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/courses/machine_learning/deepdive2/production_ml/solutions/tfdv_basic_spending_old.ipynb)`. I'd propose removing that old ipynb so others wouldn't fat finger double click that in the jupyter notebook.
