### ISSUE TITLE
Big Data & ML Fundamentals Lab 4: Recommendations ML with Dataproc v1.3: "19/02/13 12:26:23 WARN org.apache.hadoop.hdfs.DataStreamer: Caught exception java.lang.InterruptedException"

### ISSUE THREAD

**Issue by tarrade** [GoogleCloudPlatform/training-data-analyst#381]
Hi there,

just for info. In "Big Data & ML Fundamentals Lab 4: Recommendations ML with Dataproc v1.3" when running a pyspark job with Dataproc, code is running but there are "caught exception". Maybe something to be update in the config. At the end the job run and succeed. Here the full log and the following code is run:

https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/CPB100/lab3b/sparkml/train_and_apply.py

19/02/13 12:25:54 INFO org.spark_project.jetty.util.log: Logging initialized @3300ms
19/02/13 12:25:54 INFO org.spark_project.jetty.server.Server: jetty-9.3.z-SNAPSHOT, build timestamp: unknown, git hash: unknown
19/02/13 12:25:54 INFO org.spark_project.jetty.server.Server: Started @3435ms
19/02/13 12:25:54 INFO org.spark_project.jetty.server.AbstractConnector: Started ServerConnector@5a39e97c{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
19/02/13 12:25:54 WARN org.apache.spark.scheduler.FairSchedulableBuilder: Fair Scheduler configuration file not found so jobs will be scheduled in FIFO order. To use fair scheduling, configure pools in fairscheduler.xml or set spark.scheduler.allocation.file to a file that contains the configuration.
19/02/13 12:25:56 INFO org.apache.hadoop.yarn.client.RMProxy: Connecting to ResourceManager at cluster-d34e-m/10.128.0.2:8032
19/02/13 12:25:56 INFO org.apache.hadoop.yarn.client.AHSProxy: Connecting to Application History server at cluster-d34e-m/10.128.0.2:10200
19/02/13 12:25:59 WARN org.apache.hadoop.hdfs.DataStreamer: Caught exception
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1252)
	at java.lang.Thread.join(Thread.java:1326)
	at org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:980)
	at org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:630)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:807)
19/02/13 12:26:00 INFO org.apache.hadoop.yarn.client.api.impl.YarnClientImpl: Submitted application application_1550060283142_0001
19/02/13 12:26:09 WARN org.apache.spark.SparkContext: Spark is not running in local mode, therefore the checkpoint directory must not be on the local filesystem. Directory 'checkpoint/' appears to be on the local filesystem.
read ...
19/02/13 12:26:23 WARN org.apache.hadoop.hdfs.DataStreamer: Caught exception
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1252)
	at java.lang.Thread.join(Thread.java:1326)
	at org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:980)
	at org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:630)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:807)
trained ...
predicted for user=0
predicted for user=1
predicted for user=2

Thanks
Cheers
Fabien

**Comment by tarrade** [comment]
I guess with all the modifications ongoing on GCP and pyspark this is obsolete. I guess a new lab will be update to use the latest version of the various tools. Closing.
