### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: Table not initialized.

### ISSUE THREAD

**Issue by sswapnil2** [GoogleCloudPlatform/training-data-analyst#386]
2019-02-19 11:20:15.948958: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at lookup_table_op.cc:674 : Failed precondition: Table not initialized.
2019-02-19 11:20:15.948958: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at lookup_table_op.cc:674 : Failed precondition: Table not initialized.
2019-02-19 11:20:15.958287: I tensorflow/core/kernels/lookup_util.cc:376] Table trying to initialize from file ./temp_output/vocab.txt is already initialized.
Traceback (most recent call last):
  File "/home/user12/Documents/answer_evaluation_12_2_19/env3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/user12/Documents/answer_evaluation_12_2_19/env3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user12/Documents/answer_evaluation_12_2_19/env3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Table not initialized.
         [[{{node hash_table_Lookup}} = LookupTableFindV2[Tin=DT_STRING, Tout=DT_INT64, _device="/device:CPU:0"](string_to_index/hash_table, SparseToDense, string_to_index/hash_table/Const)]]
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?], [?,?], [?,1]], output_types=[DT_INT64, DT_INT64, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

During handling of the above exception, another exception occurred:

I am trying to run model native in local environment. tf.contrib.lookup.index_table_from_file throws table not initialized error.

**Comment by infinitylogesh** [comment]
did you try to initialize the table with 

`sess.run(tf.tables_initializer())`

**Comment by sswapnil2** [comment]
I am using dataset api, when should I initialise my session.?
 If I try to put it anywhere else from map function then it says table initializer should belong to same graph

**Comment by infinitylogesh** [comment]
It should be done before initialising the iterator in session run.

Example:
```
vocab = tf.contrib.lookup.index_table_from_file( ... )
dataset = tf.data.experimental.make_csv_dataset( ... )  
dataset = dataset.map( vocab.lookup( ... ) )
dataset_iter = dataset.make_initializable_iterator()
next_element = dataset_iter.get_next()

with tf.Session() as sess:
     sess.run(tf.tables_initializer())
     sess.run(dataset_iter.initializer)
     data = sess.run(next_element)

```

Hope this helps.
