### ISSUE TITLE
SyntaxError in containerengine/bonus/frontend/gcp/pubsub.js

### ISSUE THREAD

**Issue by chrisxue815** [GoogleCloudPlatform/training-data-analyst#525]
https://github.com/GoogleCloudPlatform/training-data-analyst/blob/e916f03b0274470c3f8b645106b37403043b5cee/courses/developingapps/nodejs/containerengine/bonus/frontend/gcp/pubsub.js#L37

Extra braces in are causing `SyntaxError: Unexpected token )`.

Error log:
```
> node ./app.js

/app/gcp/pubsub.js:37
});
^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/api/index.js:20:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by Archanach707** [comment]
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)  
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)      
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)    
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)   
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Sites\travel-site\gulpfile.js:3:1)    at Module._compile (internal/modules/cjs/loader.js:778:30)  
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
